"""Add dummy field

Revision ID: 33a8d5aa0831
Revises: 2af27c485b1f
Create Date: 2025-10-23 13:47:43.027842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33a8d5aa0831'
down_revision: Union[str, Sequence[str], None] = '2af27c485b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deskbooking', sa.Column('dummy', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deskbooking', 'dummy')
    # ### end Alembic commands ###
