"""Properly initialise occupancy table

Revision ID: 4e0f8c917225
Revises: 5b76b5618c4f
Create Date: 2025-11-05 10:35:10.771194

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e0f8c917225"
down_revision: Union[str, Sequence[str], None] = "5b76b5618c4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "occupancyrecord",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("desk_id", sa.String(), nullable=False),
        sa.Column("occupied", sa.Boolean(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_occupancyrecord_desk_id"), "occupancyrecord", ["desk_id"], unique=False
    )
    op.create_index(
        op.f("ix_occupancyrecord_id"), "occupancyrecord", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_occupancyrecord_timestamp"),
        "occupancyrecord",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_occupancyrecord_timestamp"), table_name="occupancyrecord")
    op.drop_index(op.f("ix_occupancyrecord_id"), table_name="occupancyrecord")
    op.drop_index(op.f("ix_occupancyrecord_desk_id"), table_name="occupancyrecord")
    op.drop_table("occupancyrecord")
    # ### end Alembic commands ###
